# -*- coding: utf-8 -*-
"""Model2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FKi0bwYRRF6uhM4BbJGLIMGcNGdcTB9

## Colecting Images Using OpenCV
"""

import os
import time
import cv2
import uuid

IMAGES_PATH = './Model/Dataset/naveen_sharma'
number_images = 50

cap = cv2.VideoCapture(0)
for imgnum in range(number_images):
    print('Collecting image {}'.format(imgnum))
    ret, frame = cap.read()
    imgname = os.path.join(IMAGES_PATH,f'img{str(imgnum)}.jpg')
    cv2.imwrite(imgname, frame)
    cv2.imshow('frame', frame)
    time.sleep(0.5)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()